# Generated by Django 5.2.5 on 2025-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='filter_columns',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='result_columns',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='enabled_sheets',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled sheets in the Excel file'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='sheet_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for each sheet including filter and result columns'),
        ),
    ]
